Chemical renaming
C2SM/processing-chain pull request #59
Opened 2024-02-05 12:31 UTC by efmkoene

Fixes https://github.com/C2SM/processing-chain/issues/37

This should eventually close https://github.com/C2SM/processing-chain/issues/37 once `async` becomes the main code. It should push back into `async` (I've never pushed a branched branch, so please check if all goes correctly).

2024-02-05 13:22 UTC, mjaehn commented
@efmkoene Thanks for this PR! I will review this one, but will set the base branch to v3.1-rc once async is merged (as it is in its final review stage).

2024-02-05 14:15 UTC, mjaehn requested changes
I would prefer to shorten the variable name.

2024-02-05 14:15 UTC, mjaehn commented on cases/icon-art-oem-test/config.yaml
> +    chem_in_to_chem_out_remap_tracers:
```suggestion
    remap_tracers:
```

2024-02-05 14:15 UTC, mjaehn commented on jobs/prepare_art_oem.py
> +                        'chem_in_to_chem_out_remap_tracers'].items():
```suggestion
            if "remap_tracers" in cfg.chem:
                for chem_in, chem_out in cfg.chem[
                        'remap_tracers'].items():
```

2024-02-05 14:43 UTC, efmkoene commented
This satisfies your review :-)

2024-02-07 18:09 UTC, mjaehn commented
launch jenkins

2024-02-08 10:27 UTC, merged